# Default values for bun-git-proxy
# This is a YAML-formatted file.

# Application configuration
app:
  name: bun-git-proxy
  port: 3000
  healthPath: /api/health

# Image configuration
image:
  repository: ghcr.io/sayjeyhi/bun-git-proxy
  tag: latest
  pullPolicy: IfNotPresent

# Deployment configuration
deployment:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

# Resource configuration
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 500Mi

# Health check configuration
healthChecks:
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
  readinessProbe:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3

# Service configuration
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

# Ingress configuration
ingress:
  enabled: true
  className: traefik
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: "web,websecure"
    traefik.ingress.kubernetes.io/router.priority: "1000"
  hosts:
    - host: git-proxy.iwaskidding.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: bun-git-proxy-tls-v2
      hosts:
        - git-proxy.iwaskidding.com

# Middleware configuration
middleware:
  enabled: true
  redirectHttps:
    enabled: true
    permanent: true

# Environment variables
env:
  NODE_ENV: production

# Labels and annotations
labels: {}
annotations: {}

# Namespace
namespace: default

# Service account
serviceAccount:
  create: false
  name: ""

# Security context
securityContext: {}
podSecurityContext: {}
