{{- if .Values.middleware.enabled -}}
{{- if .Values.middleware.redirectHttps.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "calendar-app.fullname" . }}-redirect-https
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "calendar-app.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: {{ .Values.middleware.redirectHttps.permanent }}
{{- end }}
{{- end }}
